from docx import Document

doc = Document()
doc.add_heading('Manual de Usuario y Manual Técnico - Plataforma SABOR', level=1)

doc.add_heading('1. Manual de Usuario', level=2)

doc.add_heading('1.1 Visión general', level=3)
doc.add_paragraph('SABOR es una plataforma web de recetario online que permite a usuarios registrados explorar recetas, calificarlas, guardarlas como favoritas, y crear o editar sus propias recetas. Además ofrece un flujo para solicitar imágenes generadas con IA para pasos de preparación.')

doc.add_heading('1.2 Acceso y registro', level=3)
doc.add_paragraph('1. El usuario ingresa al sitio y puede acceder a la página de inicio de sesión (/login).')
doc.add_paragraph('2. Si no tiene cuenta, puede registrarse en /registro proporcionando nombre, correo y contraseña.')
doc.add_paragraph('3. El sistema valida que el correo no exista y almacena la contraseña encriptada con BCrypt.')
doc.add_paragraph('4. Luego de iniciar sesión con correo y contraseña, el usuario es redirigido a la lista de recetas disponibles.')

doc.add_heading('1.3 Exploración de recetas', level=3)
doc.add_paragraph('1. Desde la página de recetas (/recetas), el usuario puede ver las recetas más destacadas por calificación, visitas semanales o visitas totales.')
doc.add_paragraph('2. El usuario puede buscar recetas por nombre o aplicar filtros por ingredientes.')
doc.add_paragraph('3. Al elegir una receta, puede ver el detalle completo: nombre, imagen, ingredientes, pasos, costo estimado, calificación y si ya la marcó como favorita.')

doc.add_heading('1.4 Calificar y guardar recetas', level=3)
doc.add_paragraph('1. En la vista de una receta el usuario puede calificarla mediante un valor entre 0 y 5.')
doc.add_paragraph('2. El sistema guarda la calificación del usuario y recalcula el promedio general de la receta.')
doc.add_paragraph('3. El usuario puede marcar o desmarcar la receta como favorita. Las recetas favoritas se almacenan como acciones de usuario y pueden consultarse en /recetas/misFavoritas.')

doc.add_heading('1.5 Mis recetas y edición', level=3)
doc.add_paragraph('1. En /recetas/misRecetas el usuario ve las recetas que él mismo creó.')
doc.add_paragraph('2. Puede editar la receta seleccionada en /recetas/editar, donde modifica nombre, ingredientes, pasos y la imagen asociada.')
doc.add_paragraph('3. Al editar, el usuario puede también actualizar imágenes de pasos si se cargan nuevos archivos.')

doc.add_heading('1.6 Crear una receta', level=3)
doc.add_paragraph('1. El usuario accede a /receta/agregar para crear una nueva receta.')
doc.add_paragraph('2. Debe completar los datos básicos, seleccionar ingredientes con cantidad y costos, y definir los pasos de preparación.')
doc.add_paragraph('3. Puede subir una imagen principal para la receta.')
doc.add_paragraph('4. Para cada paso puede indicar si desea generar una petición de imagen con IA ingresando una descripción de la imagen. Estas peticiones se envían en estado pendiente para revisión por un moderador.')

doc.add_heading('1.7 Peticiones de imagen con IA', level=3)
doc.add_paragraph('1. Cuando el usuario marca un paso para generar imagen con IA, la plataforma crea una petición con estado PENDIENTE.')
doc.add_paragraph('2. Un moderador puede revisar el estado de las peticiones y aprobar o denegar la generación de la imagen.')

doc.add_heading('1.8 Gestión de cuenta', level=3)
doc.add_paragraph('1. El usuario puede editar su perfil en /usuarios/editar y cambiar sus datos personales.')
doc.add_paragraph('2. En /usuarios/cambiar puede cambiar nombre, correo o contraseña.')
doc.add_paragraph('3. Para cambiar contraseña se solicita la contraseña actual y la nueva contraseña; el sistema valida la contraseña anterior antes de aceptar el cambio.')

doc.add_heading('1.9 Flujo natural de usuario', level=3)
doc.add_paragraph('1. El usuario abre la plataforma y decide si desea ingresar o registrarse.')
doc.add_paragraph('2. Tras iniciar sesión, navega las recetas disponibles y usa la búsqueda o filtros para encontrar una receta interesante.')
doc.add_paragraph('3. Visualiza detalles de una receta, la califica, la guarda como favorita o la comparte con el sistema para futuras consultas.')
doc.add_paragraph('4. Si desea contribuir, crea o edita recetas propias con ingredientes, pasos e imágenes.')
doc.add_paragraph('5. Para pasos sin imagen, puede solicitar la creación de imágenes con IA y el moderador revisa la petición.')

doc.add_heading('2. Manual Técnico', level=2)

doc.add_heading('2.1 Arquitectura general', level=3)
doc.add_paragraph('SABOR es una aplicación Java basada en Spring Boot con arquitectura MVC y capa de persistencia JPA. El proyecto está organizado en paquetes principales:')
doc.add_paragraph(' - com.flerchante.recetario.controller: controladores web y rutas HTTP.')
doc.add_paragraph(' - com.flerchante.recetario.model.entity: entidades JPA que representan tablas de la base de datos.')
doc.add_paragraph(' - com.flerchante.recetario.model.dto: objetos de transferencia para formularios compuestos.')
doc.add_paragraph(' - com.flerchante.recetario.repository: repositorios JPA que exponen operaciones de acceso a datos.')
doc.add_paragraph(' - com.flerchante.recetario.service: servicios de negocio que encapsulan la lógica de aplicación.')
doc.add_paragraph(' - com.flerchante.recetario.security: configuración de seguridad Spring Security.')

doc.add_heading('2.2 Entidades principales', level=3)
doc.add_paragraph('Usuario: representa al usuario de la plataforma. Tiene nombre, correo, contraseña encriptada y relación con un Rol. Un usuario puede crear recetas y ejecutar acciones (favorito o calificación).')
doc.add_paragraph('Rol: define el perfil del usuario (por ejemplo USER o moderador), su nombre y descripción. Se usa en seguridad para asignar roles a la sesión.')
doc.add_paragraph('Receta: representa una receta culinaria con nombre, imagen, visitas, calificación promedio y referencias a su creador, ingredientes, pasos y acciones de usuario.')
doc.add_paragraph('Ingrediente: representa un ingrediente disponible para recetas, con nombre, costo unitario, magnitud y posible imagen y patrocinador.')
doc.add_paragraph('Detalle: asocia una receta con un ingrediente, indicando cantidad y costo parcial. Se utiliza para calcular el costo total de la receta.')
doc.add_paragraph('Paso: representa un paso de preparación dentro de una receta. Puede incluir notas, imagen y una petición de IA para generar una imagen de ese paso.')
doc.add_paragraph('PeticionIA: representa una solicitud de generación de imagen con IA. Tiene un estatus (PEN/ENT/DEN) y descripción. Se vincula a un Paso.')
doc.add_paragraph('AccionUsuario: almacena interacciones de usuarios con recetas, como FAVORITO (FAV) y CALIFICACIÓN (CAL). Permite saber qué recetas marcó o calificó un usuario y conservar el detalle de la calificación.')

doc.add_heading('2.3 Repositorios', level=3)
doc.add_paragraph('Los repositorios extienden JpaRepository y proporcionan CRUD básico junto con consultas personalizadas:')
doc.add_paragraph(' - RecetaRepository: consultas para ordenar recetas por visitas semanales o totales, búsqueda por nombre y actualizaciones de visitas, nombre y calificación.')
doc.add_paragraph(' - PeticionesRepository: CRUD de peticiones de IA, actualización de estatus y creación de peticiones con SQL nativo.')
doc.add_paragraph(' - UsuarioRepository: búsqueda de usuarios por email y CRUD de usuarios.')
doc.add_paragraph(' - RolRepository: obtención de roles por id.')
doc.add_paragraph(' - IngredienteRepository, DetalleRepository, PasoRepository, AccionUsuarioRepository: CRUD para ingredientes, detalles de receta, pasos y acciones de usuario. También presentan consultas avanzadas para filtrar por ingredientes y asignar peticiones IA.')

doc.add_heading('2.4 Servicios', level=3)
doc.add_paragraph('Cada servicio implementa una interfaz y se encarga de la lógica de negocio:')
doc.add_paragraph(' - UsuarioServiceImpl: obtiene usuarios por id o email, guarda/actualiza usuarios, y consulta el usuario de la sesión actual usando Spring Security.')
doc.add_paragraph(' - RecetaServiceImpl: guarda recetas inicializando valores de visitas y calificaciones, obtiene listas, filtra por nombre, controla top semanal/total, y actualiza visitas o calificaciones en transacciones.')
doc.add_paragraph(' - PeticionesServiceImpl: gestiona peticiones de IA, las ordena, actualiza estatus y genera nuevas peticiones.')
doc.add_paragraph(' - PasoServiceImpl: actualiza pasos, guarda pasos asociados a una receta y asigna peticiones de IA a pasos.')
doc.add_paragraph(' - DetalleServiceImpl: calcula costos de detalles, guarda detalles de recetas y actualiza cantidades e ingredientes.')
doc.add_paragraph(' - IngredienteServiceImpl: lista ingredientes ordenados y obtiene ingredientes individuales.')
doc.add_paragraph(' - RolServiceImpl: obtiene roles por id.')
doc.add_paragraph(' - UserUtils: ayuda a inyectar información del usuario autenticado en el modelo para las vistas.')

doc.add_heading('2.5 Controladores', level=3)
doc.add_paragraph('LoginController: muestra la vista de login y maneja errores o mensajes de logout.')
doc.add_paragraph('RegistroController: muestra el formulario de registro y crea nuevos usuarios con rol USER y contraseña cifrada.')
doc.add_paragraph('RecetaController: la pieza central para listar recetas, ver detalles, filtrar por ingredientes, calificar, marcar favoritas, crear, editar y eliminar recetas. También maneja la vista de creación y edición de recetas y la lógica de peticiones de imagen IA en los pasos.')
doc.add_paragraph('UsuarioController: permite al usuario ver y editar su perfil, cambiar nombre, correo y contraseña, además de validar la contraseña actual por AJAX.')
doc.add_paragraph('ModeradorController: administra la vista de peticiones de imagen IA, filtra peticiones por estado, muestra detalles y permite aprobar o denegar peticiones. Solo usuarios con rol distinto a USER pueden acceder a estas operaciones.')
doc.add_paragraph('ImagenController: expone endpoints para devolver imágenes de recetas, pasos e ingredientes como bytes HTTP, y convierte archivos MultipartFile a Blob para persistencia.')

doc.add_heading('2.6 Seguridad', level=3)
doc.add_paragraph('Spring Security se configura con un SecurityFilterChain personalizado en SecurityConfig. Los puntos clave son:')
doc.add_paragraph(' - CSRF y CORS deshabilitados explícitamente.')
doc.add_paragraph(' - Login personalizado en /login con parámetros email y contrasenia.')
doc.add_paragraph(' - Redirección exitosa a /recetas y manejo de error en /login?error.')
doc.add_paragraph(' - Logout en /logout con redireccionamiento a /login?logout.')
doc.add_paragraph(' - Permiso público para rutas de inicio, login, registro, recursos estáticos y algunas páginas de recetas e imágenes.')
doc.add_paragraph(' - El resto de rutas requiere autenticación.')
doc.add_paragraph(' - UserDetailsService carga el usuario desde la base de datos usando UsuarioService y asigna roles desde el campo Rol.nombre.')
doc.add_paragraph(' - PasswordEncoder BCrypt para encriptar y verificar contraseñas.')

doc.add_heading('2.7 Configuración de conexión y base de datos', level=3)
doc.add_paragraph('La aplicación se conecta a una base de datos Oracle configurada en src/main/resources/application.properties:')
doc.add_paragraph(' - spring.datasource.url=jdbc:oracle:thin:@localhost:1521/freepdb1')
doc.add_paragraph(' - spring.datasource.driver-class-name=oracle.jdbc.OracleDriver')
doc.add_paragraph(' - spring.datasource.username=RECETARIO')
doc.add_paragraph(' - spring.datasource.password=FIS')
doc.add_paragraph(' - spring.jpa.database-platform=org.hibernate.community.dialect.Oracle12cDialect')
doc.add_paragraph(' - spring.jpa.hibernate.ddl-auto=none (la base de datos no se recrea automáticamente)')
doc.add_paragraph(' - Configuración de multipart para subir archivos: límite de 100MB por archivo y 50MB por petición.')

doc.add_heading('2.8 Generación de plantillas HTML', level=3)
doc.add_paragraph('Las vistas HTML se generan con plantillas Thymeleaf ubicadas en src/main/resources/templates. Los controladores retornan nombres de vistas que apuntan a archivos como:')
doc.add_paragraph(' - login.html, registro.html, index.html, template.html')
doc.add_paragraph(' - vistas/recetas/descubrir.html, ver.html, editar.html, agregar.html')
doc.add_paragraph(' - vistas/usuarios/editar.html, cambiar.html, usuarios.html')
doc.add_paragraph(' - vistas/moderador/peticiones.html, verPeticion.html')
doc.add_paragraph(' - vistas/ingredientes/lista.html, ver.html')
doc.add_paragraph('Los modelos se llenan con atributos como recetas, ingredientes, usuarioSesion, dto, pasoDTOs, y estados de error/éxito. Thymeleaf renderiza el contenido dinámico y muestra datos del usuario autenticado. Los recursos estáticos (CSS, JS, imágenes) se sirven desde src/main/resources/static.')

doc.add_heading('2.9 Temas relevantes adicionales', level=3)
doc.add_paragraph(' - El sistema guarda imágenes en columnas Blob de la base de datos y las entrega a los clientes vía endpoints específicos. No usa almacenamiento en disco para imágenes de recetas ni de pasos.')
doc.add_paragraph(' - Las calificaciones y favoritos se gestionan mediante la entidad AccionUsuario, separando la interacción del usuario de la entidad Receta.')
doc.add_paragraph(' - La generación de peticiones IA es un flujo de negocio que conecta los pasos de receta con aprobaciones de moderador. El estado de la petición se maneja con códigos cortos como PEN, ENT y DEN.')
doc.add_paragraph(' - Los controladores mezclan lógica de vista y etapas de negocio; la capa de servicio concentra operaciones de persistencia y cálculos como aumentar visitas o actualizar costos.')

doc.save('MANUAL_SABOR.docx')
PY