-------------------------------------------------------------------------------
CREATE TABLE ROL (
	ID_ROL      VARCHAR2(5) DEFAULT 'USER'
		CONSTRAINT ROL_ID_PK PRIMARY KEY
	,NOMBRE      VARCHAR2(10)
		CONSTRAINT ROL_NOMBRE_NN NOT NULL
	,DESCRIPCION VARCHAR2(20)
		CONSTRAINT ROL_DESCRIPCION_NN NOT NULL
);

CREATE TABLE USUARIOS (
	ID_USUARIO  NUMBER GENERATED BY DEFAULT AS IDENTITY
		CONSTRAINT USR_ID_USR_PK PRIMARY KEY
	,ID_ROL      VARCHAR2(5)
		CONSTRAINT USR_ROL_NN NOT NULL
		CONSTRAINT USR_ROL_FK
			REFERENCES ROL ( ID_ROL )
	,NOMBRE      VARCHAR2(50)
		CONSTRAINT USR_NOMBRE_NN NOT NULL
	,EMAIL       VARCHAR2(50)
		CONSTRAINT USR_EMAIL_NN NOT NULL
		CONSTRAINT USR_EMAIL_UQ UNIQUE
	,CONTRASENIA VARCHAR2(255)
		CONSTRAINT USR_CONT_NN NOT NULL
);
ALTER TABLE USUARIOS DISABLE CONSTRAINT USR_ROL_NN;

CREATE TABLE RECETAS (
	ID_RECETA              NUMBER GENERATED BY DEFAULT AS IDENTITY
		CONSTRAINT RCT_ID_REC_PK PRIMARY KEY
	,ID_USUARIO             NUMBER
		CONSTRAINT RCT_USUAR_NN NOT NULL
		CONSTRAINT RCT_USUAR_FK
			REFERENCES USUARIOS ( ID_USUARIO )
	,NOMBRE                 VARCHAR2(50)
		CONSTRAINT RCT_NOMBRE_NN NOT NULL
	,IMAGEN                 BLOB
	,VISITAS_TOTALES        NUMBER DEFAULT 0
	,VISITAS_SEMANALES      NUMBER DEFAULT 0
	,CALIFICACIONES_TOTALES NUMBER DEFAULT 0
	,CALIFICACION           NUMBER DEFAULT 0
		CONSTRAINT RCT_CALIF_CK CHECK ( CALIFICACION BETWEEN 0 AND 5 )
);

CREATE TABLE INGREDIENTES (
	ID_INGREDIENTE NUMBER GENERATED BY DEFAULT AS IDENTITY
		CONSTRAINT INGT_ID_ING_PK PRIMARY KEY
	,NOMBRE         VARCHAR2(50)
		CONSTRAINT INGT_NOMBRE_NN NOT NULL
	,COSTO_UNITARIO NUMBER
	,MAGNITUD       VARCHAR2(50)
		CONSTRAINT ING_MAGNITUD_NN NOT NULL
	,IMAGEN         BLOB
);

CREATE TABLE DETALLES (
	ID_DETALLE     NUMBER GENERATED BY DEFAULT AS IDENTITY
		CONSTRAINT DET_ID_DET_PK PRIMARY KEY
	,ID_RECETA      NUMBER
		CONSTRAINT DET_ID_REC_FK
			REFERENCES RECETAS ( ID_RECETA )
	,ID_INGREDIENTE NUMBER
		CONSTRAINT DET_ID_ING_FK
			REFERENCES INGREDIENTES ( ID_INGREDIENTE )
	,CANTIDAD       NUMBER
		CONSTRAINT DET_CANTIDAD_NN NOT NULL
	,COSTO          NUMBER
		CONSTRAINT DET_COSTO_NN NOT NULL
		CONSTRAINT DET_COSTO_CK CHECK ( COSTO >= 0 )
);

CREATE TABLE PETICION_IA (
	ID_PETICION_IA NUMBER GENERATED BY DEFAULT AS IDENTITY
		CONSTRAINT PET_IA_ID_PK PRIMARY KEY
	,ESTATUS        CHAR(3)
		CONSTRAINT PET_EST_CK CHECK ( ESTATUS IN ( 'PEN'
		                                          ,'ENT'
												  ,'DEN') )
		CONSTRAINT PET_EST_NN NOT NULL
	,DESCRIPCION    VARCHAR2(50)
		CONSTRAINT PET_DESC_NN NOT NULL
);

CREATE TABLE PASOS (
	ID_PASO     NUMBER GENERATED BY DEFAULT AS IDENTITY
		CONSTRAINT PASOS_ID_PK PRIMARY KEY
	,ID_RECETA   NUMBER
		CONSTRAINT PASOS_ID_REC_NN NOT NULL
		CONSTRAINT PASOS_ID_REC_FK
			REFERENCES RECETAS ( ID_RECETA )
	,INDICE_PASO NUMBER
		CONSTRAINT PASOS_IND_PASO_NN NOT NULL
	,NOTAS       VARCHAR2(200)
		CONSTRAINT PASOS_NOTAS_NN NOT NULL
	,IMAGEN      BLOB
	,ID_PET_IA   NUMBER
		CONSTRAINT PASOS_ID_PET_IA_FK
			REFERENCES PETICION_IA ( ID_PETICION_IA )
);

DROP TABLE DETALLES CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE ROL CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTES CASCADE CONSTRAINTS;
DROP TABLE RECETAS CASCADE CONSTRAINTS;
DROP TABLE PETICION_IA CASCADE CONSTRAINTS;
DROP TABLE PASOS CASCADE CONSTRAINTS;

-------------------------------------------------------------------------------
-- INSERTS
-------------------------------------------------------------------------------

-- ROL
INSERT INTO ROL (
	ID_ROL
	,NOMBRE
	,DESCRIPCION
) VALUES ( 'ADMIN'
          ,'Admin'
          ,'Administrador' );
INSERT INTO ROL (
	ID_ROL
	,NOMBRE
	,DESCRIPCION
) VALUES ( 'MOD'
          ,'Moderador'
          ,'Mod. peticiones IA' );
INSERT INTO ROL (
	ID_ROL
	,NOMBRE
	,DESCRIPCION
) VALUES ( 'USER'
          ,'Usuario'
          ,'Usuario regular' );
COMMIT;
-- USUARIOS
-- Assuming ID_USUARIO starts at 1 and increments.
INSERT INTO USUARIOS (
	ID_ROL
	,NOMBRE
	,EMAIL
	,CONTRASENIA
) VALUES ( 'USER'
          ,'Eduardo'
          ,'eduardo@example.com'
          ,'pass123' );
INSERT INTO USUARIOS (
	ID_ROL
	,NOMBRE
	,EMAIL
	,CONTRASENIA
) VALUES ( 'USER'
          ,'Maria'
          ,'maria@example.com'
          ,'pass123' );
INSERT INTO USUARIOS (
	ID_ROL
	,NOMBRE
	,EMAIL
	,CONTRASENIA
) VALUES ( 'USER'
          ,'Juan'
          ,'juan@example.com'
          ,'pass123' );
COMMIT;

-- INGREDIENTES
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Pechuga de Pollo'
          ,8.50
          ,'kg'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Tomate Saladet'
          ,2.50
          ,'kg'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Cebolla Blanca'
          ,1.80
          ,'kg'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Arroz Blanco'
          ,3.20
          ,'kg'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Aceite de Oliva'
          ,12.00
          ,'litro'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Sal'
          ,0.50
          ,'kg'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Pimienta Negra'
          ,1.50
          ,'100g'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Ajo'
          ,4.00
          ,'cabeza'
          ,NULL );
		  
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Huevo'
          ,0.20
          ,'unidad'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Leche'
          ,1.10
          ,'litro'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Harina de Trigo'
          ,1.50
          ,'kg'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Azúcar'
          ,1.20
          ,'kg'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Mantequilla'
          ,2.50
          ,'250g'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Papa'
          ,1.00
          ,'kg'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Zanahoria'
          ,0.80
          ,'kg'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Limón'
          ,0.30
          ,'unidad'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Queso Mozzarella'
          ,3.00
          ,'200g'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Jamón'
          ,2.80
          ,'150g'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Pan de Molde'
          ,2.00
          ,'paquete'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Carne Molida de Res'
          ,9.00
          ,'kg'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Pimiento Verde'
          ,0.60
          ,'unidad'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Champiñones'
          ,2.20
          ,'250g'
          ,NULL );
INSERT INTO INGREDIENTES (
	NOMBRE
	,COSTO_UNITARIO
	,MAGNITUD
	,IMAGEN
) VALUES ( 'Vainilla'
          ,0.50
          ,'cucharadita'
          ,NULL );

COMMIT;

-- RECETAS (Asignadas a usuarios 1, 2 y 3)
INSERT INTO RECETAS (
	ID_USUARIO
	,NOMBRE
	,IMAGEN
	,VISITAS_TOTALES
	,VISITAS_SEMANALES
	,CALIFICACION
) VALUES ( 1
          ,'Pollo en Salsa de Tomate'
          ,NULL
          ,150
          ,25
          ,4 );
INSERT INTO RECETAS (
	ID_USUARIO
	,NOMBRE
	,IMAGEN
	,VISITAS_TOTALES
	,VISITAS_SEMANALES
	,CALIFICACION
) VALUES ( 2
          ,'Arroz Blanco Perfecto'
          ,NULL
          ,200
          ,50
          ,5 );
INSERT INTO RECETAS (
	ID_USUARIO
	,NOMBRE
	,IMAGEN
	,VISITAS_TOTALES
	,VISITAS_SEMANALES
	,CALIFICACION
) VALUES ( 3
          ,'Sopa de Cebolla Gratinada'
          ,NULL
          ,80
          ,10
          ,3 );
INSERT INTO RECETAS (
	ID_USUARIO
	,NOMBRE
	,IMAGEN
	,VISITAS_TOTALES
	,VISITAS_SEMANALES
	,CALIFICACION
) VALUES ( 1
          ,'Ensalada Fresca de Verano'
          ,NULL
          ,120
          ,30
          ,4 );
INSERT INTO RECETAS (
	ID_USUARIO
	,NOMBRE
	,IMAGEN
	,VISITAS_TOTALES
	,VISITAS_SEMANALES
	,CALIFICACION
) VALUES ( 2
          ,'Pechuga de Pollo a la Plancha'
          ,NULL
          ,300
          ,75
          ,5 );
COMMIT;

UPDATE RECETAS
   SET ID_USUARIO = 1,NOMBRE = 'Ensalada Fresca de Verano'
,IMAGEN = NULL
,VISITAS_TOTALES = 120
,VISITAS_SEMANALES = 30
,CALIFICACION = 4
 WHERE ID_RECETA = 4;

-- DETALLES
-- Para Receta 1: Pollo en Salsa de Tomate
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 1
          ,1
          ,0.5
          ,4.25 ); -- 0.5 kg de Pollo
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 1
          ,2
          ,0.3
          ,0.75 ); -- 0.3 kg de Tomate
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 1
          ,3
          ,0.1
          ,0.18 ); -- 0.1 kg de Cebolla
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 1
          ,8
          ,0.05
          ,0.20 ); -- Ajo

-- Para Receta 2: Arroz Blanco Perfecto
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 2
          ,4
          ,0.25
          ,0.80 ); -- 0.25 kg de Arroz
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 2
          ,5
          ,0.02
          ,0.24 ); -- 20 ml de Aceite
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 2
          ,6
          ,0.01
          ,0.01 ); -- Sal al gusto

-- Para Receta 3: Sopa de Cebolla Gratinada
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 3
          ,3
          ,0.5
          ,0.90 ); -- 0.5 kg de Cebolla

-- Para Receta 4: Ensalada Fresca de Verano
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 4
          ,2
          ,0.2
          ,0.50 ); -- 0.2 kg de Tomate
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 4
          ,3
          ,0.1
          ,0.18 ); -- 0.1 kg de Cebolla
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 4
          ,5
          ,0.03
          ,0.36 ); -- 30 ml de Aceite

-- Para Receta 5: Pechuga de Pollo a la Plancha
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 5
          ,1
          ,0.2
          ,1.70 ); -- 0.2 kg de Pollo
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 5
          ,6
          ,0.01
          ,0.01 ); -- Sal
INSERT INTO DETALLES (
	ID_RECETA
	,ID_INGREDIENTE
	,CANTIDAD
	,COSTO
) VALUES ( 5
          ,7
          ,0.005
          ,0.07 ); -- Pimienta
COMMIT;

-- PETICION_IA
INSERT INTO PETICION_IA (
	ESTATUS
	,DESCRIPCION
) VALUES ( 'PEN'
          ,'Generar imagen para pollo con tomate' );
INSERT INTO PETICION_IA (
	ESTATUS
	,DESCRIPCION
) VALUES ( 'ENT'
          ,'Generar imagen de arroz blanco esponjoso' );
INSERT INTO PETICION_IA (
	ESTATUS
	,DESCRIPCION
) VALUES ( 'PEN'
          ,'Sugerir pasos para sopa de cebolla' );
INSERT INTO PETICION_IA (
	ESTATUS
	,DESCRIPCION
) VALUES ( 'ENT'
          ,'Imagen para ensalada de verano' );
INSERT INTO PETICION_IA (
	ESTATUS
	,DESCRIPCION
) VALUES ( 'PEN'
          ,'Generar imagen de pechuga a la plancha jugosa' );
COMMIT;

-- PASOS
-- Para Receta 1: Pollo en Salsa de Tomate
INSERT INTO PASOS (
	ID_RECETA
	,INDICE_PASO
	,NOTAS
	,IMAGEN
	,ID_PET_IA
) VALUES ( 1
          ,1
          ,'Cortar el pollo en cubos y sazonar con sal y pimienta.'
          ,NULL
          ,NULL );
INSERT INTO PASOS (
	ID_RECETA
	,INDICE_PASO
	,NOTAS
	,IMAGEN
	,ID_PET_IA
) VALUES ( 1
          ,2
          ,'Sofreír la cebolla y el ajo picados. Añadir el tomate triturado y cocinar por 10 minutos.'
          ,NULL
          ,1 );
INSERT INTO PASOS (
	ID_RECETA
	,INDICE_PASO
	,NOTAS
	,IMAGEN
	,ID_PET_IA
) VALUES ( 1
          ,3
          ,'Agregar el pollo a la salsa y cocinar a fuego lento hasta que esté bien cocido.'
          ,NULL
          ,NULL );

-- Para Receta 2: Arroz Blanco Perfecto
INSERT INTO PASOS (
	ID_RECETA
	,INDICE_PASO
	,NOTAS
	,IMAGEN
	,ID_PET_IA
) VALUES ( 2
          ,1
          ,'Lavar el arroz hasta que el agua salga clara.'
          ,NULL
          ,NULL );
INSERT INTO PASOS (
	ID_RECETA
	,INDICE_PASO
	,NOTAS
	,IMAGEN
	,ID_PET_IA
) VALUES ( 2
          ,2
          ,'En una olla, calentar el aceite y sofreír el arroz por 2 minutos.'
          ,NULL
          ,2 );
INSERT INTO PASOS (
	ID_RECETA
	,INDICE_PASO
	,NOTAS
	,IMAGEN
	,ID_PET_IA
) VALUES ( 2
          ,3
          ,'Añadir el doble de agua que de arroz, sal al gusto, y llevar a ebullición. Bajar el fuego, tapar y cocinar por 15 minutos.'
          ,NULL
          ,NULL );

-- Para Receta 5: Pechuga de Pollo a la Plancha
INSERT INTO PASOS (
	ID_RECETA
	,INDICE_PASO
	,NOTAS
	,IMAGEN
	,ID_PET_IA
) VALUES ( 5
          ,1
          ,'Sazonar la pechuga de pollo con sal y pimienta por ambos lados.'
          ,NULL
          ,NULL );
INSERT INTO PASOS (
	ID_RECETA
	,INDICE_PASO
	,NOTAS
	,IMAGEN
	,ID_PET_IA
) VALUES ( 5
          ,2
          ,'Calentar una plancha o sartén a fuego medio-alto con un poco de aceite.'
          ,NULL
          ,5 );
INSERT INTO PASOS (
	ID_RECETA
	,INDICE_PASO
	,NOTAS
	,IMAGEN
	,ID_PET_IA
) VALUES ( 5
          ,3
          ,'Cocinar la pechuga por 4-5 minutos por cada lado, hasta que esté dorada y cocida por dentro.'
          ,NULL
          ,NULL );
COMMIT;

SELECT COUNT(*) FROM RECETAS;

SELECT *
  FROM RECETAS
 WHERE LOWER(NOMBRE) LIKE 'lowername';

SELECT ID_RECETA
		,SUM(COSTO)
  FROM DETALLES 
  JOIN RECETAS USING (ID_RECETA)
 GROUP BY ID_RECETA;

SELECT ID_RECETA
		,ID_INGREDIENTE
  FROM DETALLES
 WHERE ID_INGREDIENTE IN (1, 2);

SELECT ID_RECETA
  FROM DETALLES
INTERSECT
SELECT ID_RECETA
  FROM DETALLES
  JOIN INGREDIENTES USING(ID_INGREDIENTE)
 WHERE ID_INGREDIENTE IN (1, 2);


SELECT ID_RECETA
	,COSTO_UNITARIO
	,CANTIDAD
	, (CANTIDAD * COSTO_UNITARIO)	AS REVISION
  FROM DETALLES
  JOIN INGREDIENTES USING (ID_INGREDIENTE);

UPDATE DETALLES D
   SET D.COSTO = (SELECT I.COSTO_UNITARIO * D.CANTIDAD
                    FROM INGREDIENTES I
                   WHERE I.ID_INGREDIENTE = D.ID_INGREDIENTE)
 WHERE EXISTS (SELECT 1
                 FROM INGREDIENTES I
                WHERE I.ID_INGREDIENTE = D.ID_INGREDIENTE);
COMMIT;