CONN RECETARIO/FIS@PDB

DROP TABLE DETALLES CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE ROL CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTES CASCADE CONSTRAINTS;
DROP TABLE RECETAS CASCADE CONSTRAINTS;
DROP TABLE PETICION_IA CASCADE CONSTRAINTS;
DROP TABLE PASOS CASCADE CONSTRAINTS;
DROP TABLE ACCIONUSUARIO CASCADE CONSTRAINTS;
DROP TABLE PATROCINADOR CASCADE CONSTRAINTS;